-- Create presale_signups table if it doesn't exist
CREATE TABLE IF NOT EXISTS presale_signups (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  email text not null,
  wallet_address text not null,
  amount_interested numeric,
  status text default 'pending' check (status in ('pending', 'approved', 'rejected')),
  UNIQUE(email),
  UNIQUE(wallet_address)
);

-- Enable Row Level Security on presale_signups
ALTER TABLE presale_signups ENABLE ROW LEVEL SECURITY;

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_presale_signups_email ON presale_signups(email);
CREATE INDEX IF NOT EXISTS idx_presale_signups_wallet ON presale_signups(wallet_address);
CREATE INDEX IF NOT EXISTS idx_presale_signups_status ON presale_signups(status);

-- Policies for presale_signups

-- Allow users to insert their own signup
CREATE POLICY "Allow users to create own signup" ON presale_signups 
FOR INSERT WITH CHECK (true);

-- Allow users to view their own signup
CREATE POLICY "Allow users to view own signup" ON presale_signups 
FOR SELECT USING (
  email = auth.jwt() ->> 'email' OR 
  wallet_address = auth.jwt() ->> 'address'
);

-- Allow admin to view all signups
CREATE POLICY "Allow admin to view all signups" ON presale_signups 
FOR SELECT USING (
  auth.jwt() ->> 'address' = '0xf8Ca9dA64Bb500C4C4395f7Bb987De3e77883130'
);

-- Allow admin to update signup status
CREATE POLICY "Allow admin to update signups" ON presale_signups 
FOR UPDATE USING (
  auth.jwt() ->> 'address' = '0xf8Ca9dA64Bb500C4C4395f7Bb987De3e77883130'
);

-- Create a function to export presale signups to CSV format
CREATE OR REPLACE FUNCTION export_presale_signups_csv()
RETURNS TABLE (
  csv_line text
) AS $$
BEGIN
  -- Return header row
  RETURN QUERY SELECT 'email,wallet_address,amount_interested,status,created_at'::text;
  
  -- Return data rows
  RETURN QUERY 
  SELECT 
    format('%s,%s,%s,%s,%s',
      email,
      wallet_address,
      COALESCE(amount_interested::text, ''),
      status,
      created_at::text
    )
  FROM presale_signups
  ORDER BY created_at DESC;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Grant execute permission on the export function to authenticated users
GRANT EXECUTE ON FUNCTION export_presale_signups_csv() TO authenticated;

-- Add comment to the table
COMMENT ON TABLE presale_signups IS 'Stores Axium token founders sale signups from Eko NFT holders';
