create table drops (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  city text not null,
  sponsor jsonb,
  eko_needed text,
  rewards jsonb,
  competitors integer default 0 not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null
);

-- Enable Row Level Security
alter table drops enable row level security;

-- Policies for drops
create policy "Allow public read access" on drops for select using (true);
create policy "Allow admin write access" on drops for insert with check (auth.jwt() ->> 'address' = '0xf8Ca9dA64Bb500C4C4395f7Bb987De3e77883130');
create policy "Allow admin update access" on drops for update with check (auth.jwt() ->> 'address' = '0xf8Ca9dA64Bb500C4C4395f7Bb987De3e77883130');

-- Enable real-time on the drops table
alter publication supabase_realtime add table drops;

-- Create a function to increment competitors
create or replace function increment_competitors(drop_id bigint)
returns void as $$
begin
  update public.drops
  set competitors = competitors + 1
  where id = drop_id;
end;
$$ language plpgsql; 