-- Add description and leaked_location_image columns to drops table
ALTER TABLE drops 
ADD COLUMN IF NOT EXISTS description text,
ADD COLUMN IF NOT EXISTS leaked_location_image text;

-- Update the admin delete policy
DROP POLICY IF EXISTS "Allow admin delete access" ON drops;
CREATE POLICY "Allow admin delete access" ON drops 
FOR DELETE USING (auth.jwt() ->> 'address' = '0xf8Ca9dA64Bb500C4C4395f7Bb987De3e77883130');

-- Create registrations table if it doesn't exist
CREATE TABLE IF NOT EXISTS registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default now() not null,
  drop_id bigint references drops(id) on delete cascade not null,
  wallet_address text not null,
  UNIQUE(drop_id, wallet_address)
);

-- Enable Row Level Security on registrations
ALTER TABLE registrations ENABLE ROW LEVEL SECURITY;

-- Policies for registrations
CREATE POLICY "Allow public read for own registrations" ON registrations 
FOR SELECT USING (auth.jwt() ->> 'address' = wallet_address);

CREATE POLICY "Allow public insert for own registrations" ON registrations 
FOR INSERT WITH CHECK (auth.jwt() ->> 'address' = wallet_address);

-- Update the increment_competitors function to handle registrations
CREATE OR REPLACE FUNCTION increment_competitors(drop_id bigint, wallet_address text)
RETURNS void AS $$
BEGIN
  -- First insert registration (will fail if duplicate)
  INSERT INTO public.registrations (drop_id, wallet_address) 
  VALUES (drop_id, wallet_address);
  
  -- If successful, increment competitors
  UPDATE public.drops
  SET competitors = competitors + 1
  WHERE id = drop_id;
END;
$$ LANGUAGE plpgsql; 