import React from 'react';

export default function TermsPage() {
  return (
    <div className="min-h-screen pt-20">
      <div className="container mx-auto px-4 py-16">
        {/* Header */}
        <div className="text-center mb-16">
          <h1 className="text-4xl font-bold bg-gradient-to-r from-[#2DD4BF] via-[#EC4899] to-[#2DD4BF] bg-clip-text text-transparent mb-4">
            Terms & Conditions
          </h1>
          <p className="text-gray-400">Last updated: June 21, 2025</p>
        </div>

        {/* Content */}
        <div className="max-w-4xl mx-auto space-y-8">
          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Introduction</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>Welcome to Scavenjer! These Terms and Conditions (“Terms”) govern your access to and use of the Scavenjer platform, a global scavenger hunt service that rewards users with digital assets via the Marbleverse platform. By accessing or using Scavenjer (the “Service”), you agree to be bound by these Terms. If you do not agree, you must not use the Service.</p>
              <p>We may update these Terms from time to time by posting the revised Terms on our website or app, and updating the “Last Updated” date. Your continued use of Scavenjer after changes are posted constitutes your acceptance of the revised Terms.</p>
              <p><strong>About Scavenjer:</strong> Scavenjer allows users to participate in scavenger hunts that blend real-world exploration with digital rewards. The platform leverages the Marbleverse augmented reality platform to create interactive hunts in the real world. Successful participants can receive digital assets (such as collectibles or tokens) as prizes, which are delivered through the third-party Marbleverse infrastructure. Additional third-party services, including Supabase, are used to provide backend functionality (database, authentication, etc.).</p>
              <p>Please review these Terms carefully to understand your rights and responsibilities when using Scavenjer.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Eligibility</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p><strong>Minimum Age:</strong> You must be at least 13 years old to use Scavenjer. The Service is not intended for children under 13, and we do not knowingly permit anyone under 13 to register or participate. By using Scavenjer, you affirm that you are at least 13 years of age (or the age of digital consent in your country, if higher). If you are between 13 and the age of majority in your jurisdiction, you should use the Service only with the involvement of a parent or guardian who agrees to these Terms. Scavenjer is not directed to children and does not knowingly collect personal data from children under 13 (see our Privacy Policy for more information). We reserve the right to terminate or restrict accounts that appear to be used by underage persons.</p>
              <p><strong>Other Eligibility Criteria:</strong> You represent that you have not been previously banned from using our Service and that your use of Scavenjer will not violate any applicable law or regulation. You are responsible for ensuring that using Scavenjer is legal in your location, and you must comply with all local laws while participating in hunts.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Account Registration and Security</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p><strong>Account Creation:</strong> To participate in Scavenjer hunts and receive rewards, you may need to create an account by providing certain information such as a valid email address and a digital wallet address. You agree to provide accurate, current, and complete information during registration and to keep it updated. You are responsible for maintaining the confidentiality of any login credentials and for all activities that occur under your account. If account creation is done via third-party login or wallet authentication, you must also abide by those third-party terms.</p>
              <p><strong>Account Security:</strong> You agree to use a strong, unique password and to protect your wallet credentials or private keys. Do not share your account or login details with others. If you suspect any unauthorized use of your account or a security breach, you must notify us immediately. We are not liable for any loss or damage arising from your failure to secure your account. (Note: Scavenjer will never ask you for your password or private keys via email or unsolicited communication.)</p>
              <p><strong>Single Account:</strong> Each user is generally limited to one account. Creating multiple accounts to gain unfair advantages (for example, to bypass participation limits or obtain extra rewards) is prohibited. You also agree not to impersonate any person or entity or use someone else's email or wallet in your account creation.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">User Conduct and Acceptable Use</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>By using Scavenjer, you agree to follow these rules of conduct to ensure a safe and fair experience for all users:</p>
              <ul className="list-disc pl-6 space-y-3">
                <li><strong>Abide by the Law:</strong> You will not use the Service to violate any applicable law or regulation, and you will not encourage or enable anyone else to do so. This includes all local laws regarding trespassing, public conduct, and road safety. Always obtain appropriate permissions if a scavenger hunt clue or reward is located on private property.</li>
                <li><strong>Safety and Awareness:</strong> You agree to be aware of your surroundings and use the Service safely at all times. Participating in scavenger hunts may involve physical activity and real-world exploration. You are solely responsible for exercising caution—do not enter dangerous areas, do not engage in unsafe behavior, and never attempt hunts while driving or distracted. Your use of the Service is at your own risk, and you assume all responsibility for any injuries, damages, or losses that you may incur through participation. Scavenjer disclaims liability for any accidents or incidents that occur during your hunt activities (see Section 11 on Liability).</li>
                <li><strong>No Cheating or Fraud:</strong> Cheating undermines the spirit of the game and is strictly prohibited. You will not engage in any fraud or cheating behavior, including but not limited to: using unauthorized software or modified apps, GPS spoofing or falsifying your location, exploiting bugs or vulnerabilities, creating multiple accounts, or any other technique to unfairly gain advantage. Scavenjer may employ anti-cheat measures to detect and prevent such behavior. Users found cheating may be disqualified from rewards, have their accounts suspended, or be banned from the platform.</li>
                <li><strong>No Unauthorized Content or Activities:</strong> You will not upload or transmit any content through Scavenjer (if future features allow) that is illegal, obscene, hateful, or infringes on anyone's rights. (Currently, Scavenjer does not host user-generated content uploads, so this primarily applies to communications or future content features.) You will also not use the Service for any commercial purpose not expressly approved by us, such as advertising or selling products, nor for any activity that is malicious (e.g., introducing viruses, malware, or conducting attacks on the Service infrastructure).</li>
                <li><strong>Respect Others:</strong> If Scavenjer enables social features (such as competing in teams or events), you agree to interact respectfully with others. Harassment, threats, stalking, or abuse of other participants are not allowed. You will not interfere with another user's enjoyment of the Service, and you will not attempt to collect or harvest personal data about other users.</li>
                <li><strong>No Network Abuse:</strong> You will not attempt to disrupt or overwhelm the Service. Prohibited activities include: interfering with servers or networks (e.g., no DDoS attacks, spam, or hacking attempts), injecting malicious code, or otherwise attempting to gain unauthorized access to our systems. You also agree not to reverse engineer or decompile the Service's software, not to scrape or data-mine our content, and not to bypass any security or access controls. Any such attempts may result in immediate termination of your access and potential legal action.</li>
              </ul>
              <p>We reserve the right to monitor compliance with these rules and to investigate any alleged violations. If you violate the above conduct standards or any other provision of these Terms, we may take enforcement action, including issuing warnings, removing you from a hunt, withholding rewards, suspending or terminating your account, and/or involving law enforcement if necessary.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Rewards and Digital Assets</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>One of the unique features of Scavenjer is the ability to earn digital rewards for completing scavenger hunt challenges. Please read this section carefully to understand how rewards work and the terms associated with them:</p>
              <ul className="list-disc pl-6 space-y-3">
                <li>
                  <strong>Reward Description:</strong> Rewards may consist of various items, including:
                  <ul className="list-disc pl-6 space-y-2 mt-2">
                    <li>
                      <strong>Digital Assets:</strong> Such as NFTs (known as Ekos in our ecosystem) or other blockchain-based tokens, delivered via the Marbleverse platform. Marbleverse is an augmented reality metaverse that uses virtual "Marbles" as containers for digital content. When you successfully complete a scavenger hunt, you might receive a Marble or similar digital token that can represent your prize (for example, a collectible badge, a piece of digital art, or other virtual item). These assets are typically stored on a blockchain or within the Marbleverse app ecosystem.
                    </li>
                    <li>
                      <strong>Physical items:</strong> Such as limited-edition Scavenjer merchandise, collectibles, or other tangible goods. These items may be redeemed through Scavenjer directly or through specific claim processes outlined during the campaign or event.
                    </li>
                    <li>
                      <strong>Promotional items or experiences:</strong> Which may be provided in partnership with third-party sponsors, local businesses, or other affiliates. These can include discounts, vouchers, exclusive offers, or access to branded experiences or products. Availability and terms for promotional rewards may vary by location, event, and participating sponsor.
                    </li>
                  </ul>
                  <p className="mt-2">
                    The exact nature of each reward will be specified in the details of the applicable scavenger hunt or campaign. Some rewards may have eligibility requirements, expiration dates, or redemption instructions, which will be clearly communicated at the time of offer.
                  </p>
                </li>
                <li><strong>Wallet and Marbleverse Account:</strong> To claim or receive a digital asset reward, you may need a compatible digital wallet (e.g., an Ethereum wallet or other blockchain wallet, depending on the asset) or a Marbleverse account. Scavenjer will generally distribute rewards by linking them to the wallet address you provide us. Ensure you provide a correct and operational wallet address; providing an incorrect address may result in permanent loss of the reward, for which we cannot be responsible. In some cases, rewards might be claimed through the Marbleverse application or website, which could require you to create a Marbleverse account and accept Marbleverse's Terms of Use and Privacy Policy. The Marbleverse End User License Agreement and platform rules will apply to your use of that platform. We will provide instructions at the time of reward distribution on how to claim your prize.</li>
                <li><strong>Third-Party Platform:</strong> Please note that Marbleverse is independent from Scavenjer. We facilitate the hunt and qualification for the reward, but the delivery and ongoing management of the digital asset may be handled by Marbleverse or the underlying blockchain. Scavenjer has no control over the Marbleverse platform or the blockchain's performance, and makes no guarantees about the availability, functionality, or stability of Marbleverse's services. By accepting a Scavenjer reward, you acknowledge that any interaction with the Marbleverse platform or any blockchain network is at your own risk and subject to Marbleverse's terms. We encourage you to review Marbleverse's policies (e.g., their Terms of Use and Privacy Policy) for details on their service.</li>
                <li><strong>Value & Taxes:</strong> Some digital rewards offered by Scavenjer may carry redeemable or monetary value, including the potential for use within Scavenjer's in-house market, exchange for goods, services, or other forms of compensation as defined by the platform. However, the availability and conditions of such value-based rewards are determined solely by Scavenjer and are subject to change, eligibility, and specific program terms.

While certain digital assets may become tradable or sellable, either within Scavenjer's ecosystem or through third-party marketplaces, Scavenjer does not guarantee or set the market value of any asset beyond what is explicitly offered in-platform.

If you receive a digital asset or reward that acquires market or redeemable value, you are solely responsible for any associated tax obligations, including income or capital gains tax. Scavenjer does not provide tax advice or tax documentation. We encourage you to consult a tax professional to understand your personal responsibilities.</li>
                <li><strong>Reward Availability and Substitution:</strong> We strive to fulfill all reward distributions promptly. However, all rewards are subject to availability and technical feasibility. In rare cases, if a promised digital reward becomes unavailable or technically impracticable to deliver, we reserve the right to substitute it with another reward of comparable value or to provide an alternative form of compensation (such as a future credit or a different digital item). We will inform affected users of any necessary changes.</li>
                <li><strong>Forfeiture and Disqualification:</strong> If we determine that you have violated these Terms or the hunt rules in obtaining a reward (for example, through cheating or fraudulent means), we reserve the right to disqualify you from the reward. This may include not delivering the digital asset or, if it has already been delivered, taking appropriate action (to the extent possible) to invalidate or retrieve the reward. We also reserve the right to deny future participation in hunts if a user is found to be abusing the system. Additionally, if you fail to claim a reward within a specified time period (we will notify you of any claim deadlines), you may forfeit that reward.</li>
                <li><strong>User Responsibilities for Digital Assets:</strong> Once a digital asset reward is delivered to your wallet or Marbleverse account, you are solely responsible for managing and safeguarding it. This includes keeping your wallet secure (protecting your private keys or seed phrases) and following Marbleverse's guidelines for asset storage. Scavenjer cannot recover lost or inaccessible digital assets (for example, if you lose your private key or send the asset to an incorrect address). We also are not responsible for any damage or loss of the asset due to issues on the Marbleverse platform or the underlying blockchain (such as network failures, smart contract bugs, or third-party hacks).</li>
              </ul>
              <p>In summary, we want our users to enjoy the innovative rewards Scavenjer offers, but it's important to understand the conditions and risks inherent to digital assets. If you have any questions about how rewards work, please contact us before participating.</p>
            </div>
          </section>
          
          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Future Paid Services and Subscriptions</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>Scavenjer is currently free to use. However, we plan to introduce optional paid services in the future – for example, a premium subscription pass (such as a "Scavenjer Pass") that provides additional features or benefits to subscribers. This section outlines anticipated terms related to future monetization, although specifics may change when these services launch:</p>
              <ul className="list-disc pl-6 space-y-3">
                <li><strong>Subscription Features:</strong> A subscription pass might offer perks like exclusive scavenger hunts, early access to new features, enhanced rewards, an ad-free experience, or other premium content. Details will be announced when the subscription is available.</li>
                <li><strong>Fees and Payment:</strong> If you choose to subscribe, you will be required to pay the subscription fee indicated at the time of purchase. Subscription fees may be charged on a recurring basis (e.g., monthly or annually). By enrolling, you authorize us (or our payment processor) to charge your provided payment method for the initial term and recurring terms until you cancel. Prices will be clearly communicated in your local currency when possible, and any applicable taxes will be added as required by law.</li>
                <li><strong>Payment Processing:</strong> We will use a secure third-party payment processor (such as Stripe, PayPal, or similar) to handle your payment information. Scavenjer itself will not store your full credit card number or bank details; all such sensitive financial information is handled by the payment processor in accordance with their privacy policy. By subscribing, you also agree to the payment processor's terms of service as applicable.</li>
                <li><strong>Auto-Renewal and Cancellation:</strong> Subscriptions will auto-renew by default at the end of each billing cycle (e.g., your subscription will automatically renew each month or year) unless you cancel beforehand. You can cancel a subscription at any time by following the instructions in your account settings or contacting our support. If you cancel, your subscription benefits will continue until the end of the current paid term, and no further charges will be made. However, no pro-rated refunds are typically provided for mid-term cancellations (unless required by law or stated otherwise). We will notify you of any significant changes to the auto-renewal terms or pricing.</li>
                <li><strong>Free Trials and Promotions:</strong> We may offer free trials or introductory offers for subscriptions. Such offers are only for new subscribers (unless stated otherwise) and must be used in accordance with their terms. After a free trial period ends, if you have not cancelled, we may begin charging the applicable subscription fee. We will remind you of this in the offer details. Only one trial per user is allowed. Abuse of trial offers (such as creating multiple accounts to get repeated trials) is a violation of these Terms.</li>
                <li><strong>Changes to Fees:</strong> Our subscription pricing and structure may evolve. If we change subscription fees or introduce new charges, we will give subscribers reasonable advance notice (for example, by email and/or a notice within the app). Any fee increase will apply only to subsequent billing cycles, not the current one, and if you do not agree to the new price, you can cancel the subscription before the next renewal. Continued use of the subscription service after a price change takes effect will constitute your agreement to pay the new amount.</li>
                <li><strong>Subscription Content and License:</strong> Any premium content or digital goods provided as part of a subscription are for personal, non-transferable, non-commercial use only (unless explicitly allowed). Subscribers receive a limited, revocable license to access the subscription content during the subscription term. All such content remains the property of Scavenjer or its licensors, and is protected by intellectual property laws. If your subscription ends or is terminated, you may lose access to subscriber-only content or features.</li>
              </ul>
              <p>These subscription terms are provided for transparency ahead of the feature's launch. When we roll out paid subscriptions, we may issue additional or updated terms to reflect the specifics at that time, and you will need to agree to those terms in order to subscribe.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Third-Party Services and Links</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>Scavenjer integrates with, or provides links to, certain third-party services to function effectively and enhance your experience. This section explains your relationship with those third parties:</p>
              
              <p><strong>Marbleverse Platform:</strong> As noted, Scavenjer uses the Marbleverse augmented reality platform to host and deliver scavenger hunt content and rewards. Marbleverse is operated by Marble AR, Inc., and has its own End User License Agreement (EULA) and Privacy Policy. When you use Marbleverse features through Scavenjer (for example, when discovering or dropping virtual "Marbles" in AR hunts, or when claiming a Marbleverse-hosted reward), you are also subject to Marbleverse's terms and policies. We encourage you to review Marbleverse's EULA and Privacy Policy, which can be found on their official website and app (e.g., via the Marbleverse app's settings or on their website). Scavenjer is not responsible for Marbleverse's services, content, or data practices. Any issues arising from the use of Marbleverse (such as app crashes, AR functionality, or data collected by Marbleverse) are governed by your agreement with Marbleverse, not by Scavenjer. That said, we value our collaboration with Marbleverse and aim to ensure a smooth integration; if you encounter problems specifically with how Scavenjer interfaces with Marbleverse, you can report them to us and we will try to assist or direct you to the appropriate support.</p>

              <p><strong>Supabase:</strong> We use Supabase, an open-source backend-as-a-service, as part of our infrastructure (for data storage, user authentication, etc.). Supabase acts as a data processor on our behalf, which means it stores and processes user data under our instructions. Supabase's role is largely behind-the-scenes, and you typically will not interact with Supabase directly. However, because it handles personal information (such as your email and login credentials) on our behalf, we want you to be aware of its involvement. Supabase is a reputable service with strong security measures (it is SOC 2 Type 2 compliant and uses encryption for data at rest and in transit). Your use of Scavenjer implies consent to this sub-processing. Supabase's own Privacy Policy is available on their website, and it outlines how they handle data in their systems. We have a Data Processing Addendum in place with Supabase to ensure your data is handled in compliance with privacy regulations.</p>

              <div>
                <p><strong>Other Third-Party Providers:</strong> In operating Scavenjer, we may also utilize additional third-party services such as map providers, email service providers, analytics tools, or payment processors. For example:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>If we display maps or location data, we might integrate APIs like Google Maps (which would be used under Google's terms and may collect certain device/location information).</li>
                  <li>If we send email newsletters or notifications, we might use an email delivery service (like SendGrid or MailChimp), which would handle your email address under their terms.</li>
                  <li>For processing payments (for future subscriptions or merchandise), we will use established payment processors (e.g., Stripe or PayPal) as noted in Section 6, and your payment transaction will be subject to those providers' terms and privacy policies.</li>
                </ul>
                <p className="mt-2">We will provide disclosures about specific third-party integrations in our Privacy Policy or at the point of interaction, as required.</p>
              </div>

              <p><strong>Links to Third-Party Sites:</strong> Our website or app may contain links to third-party websites or resources that are not owned or controlled by Scavenjer (for example, a link to a sponsor's site, a social media page, or Marbleverse's own website). These links are provided for your convenience or as part of the game experience. We do not endorse and are not responsible for the content, products, services, or practices of any third-party websites. Once you click a third-party link and leave the Scavenjer environment, these Terms no longer apply; instead, the terms of use and privacy policy of that third-party site will govern. We recommend you review the policies of any third-party site you visit. Scavenjer will not be liable for any loss or damage that may arise from your use of third-party sites or services.</p>

              <p><strong>Third-Party Content in Hunts:</strong> In some scavenger hunts, clues or rewards might involve third-party content or locations (for example, a clue might direct you to a public landmark, a business, or an online resource like a Wikipedia page). Any third-party content used in hunts is for game purposes only. Scavenjer does not claim ownership of such third-party content and usage is intended under fair use or with permission. If you believe any third-party intellectual property is being misused in our Service, please notify us.</p>
              
              <p>In summary, while Scavenjer coordinates an ecosystem of services to deliver a seamless scavenger hunt experience, not everything is under our direct control. Your interactions with third-party platforms are partly at your discretion and subject to their rules. We aim to choose reliable, security-conscious partners, but we cannot guarantee their performance. If a third-party service used by Scavenjer becomes unavailable or causes an issue, we will do our best to minimize impact on you (for instance, by finding alternative solutions or assisting in communication with that service's support), but we are not liable for the failings of third parties (see Section 11).</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Intellectual Property Rights</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <div>
                <p><strong>Scavenjer Content:</strong> All content and materials available on the Scavenjer platform— including but not limited to text, graphics, logos, button icons, images, videos, software code, and the overall design and “look and feel” of the Service — are the property of Scavenjer or its licensors and are protected by copyright, trademark, and other intellectual property laws. “Scavenjer” and our logos, slogans, or taglines are trademarks/service marks of our company. You are granted a limited, non-exclusive, non-transferable license to access and use the Service and its content for your personal, non-commercial use only, in accordance with these Terms. Except as expressly permitted by us in writing, you must not:</p>
                <ul className="list-disc pl-6 mt-2 space-y-2">
                  <li>Copy, reproduce, distribute, publish, or publicly display any part of the Service or its content (except as enabled within the platform, such as sharing a scavenger hunt invite with friends through provided tools).</li>
                  <li>Modify or create derivative works of the Service or content.</li>
                  <li>Reverse engineer, decompile, or attempt to extract the source code of any software or databases within the Service.</li>
                  <li>Use any of our trademarks or logos without our prior written permission.</li>
                </ul>
              </div>
              <p><strong>Marbleverse and Third-Party Content:</strong> The Marbleverse platform and related marks are the intellectual property of Marble AR, Inc. (or other owners). Scavenjer does not own Marbleverse's content, AR technology, or the digital assets distributed via Marbleverse. Those remain subject to Marbleverse's own intellectual property rights and terms. Additionally, any third-party content incorporated into hunts (e.g., a Wikipedia excerpt in an "Info Marble", or images/characters that are part of a clue) are owned by the respective third parties. Our use of such content is either under license, partnership, user-generated input, or believed to be permissible under applicable law (such as fair use). These Terms do not grant you any rights to third-party intellectual property, and you must not use any third-party content from the Service beyond what is allowed within the Service itself.</p>
              <p><strong>User Contributions:</strong> Currently, Scavenjer does not have a feature for users to post or upload their own content directly to our site/service (aside from possibly submitting location suggestions or communicating with us). In the event that we enable any user-generated content features in the future (for example, if users can create their own hunts or share photos/comments within the app), any content you submit would remain your property, but you would grant Scavenjer a broad license to use that content for the purposes of operating, promoting, and improving the Service. Specifically, you would grant us a worldwide, royalty-free, sublicensable license to host, reproduce, distribute, modify (for technical display purposes, e.g., resizing images), publicly display, and perform your content in connection with the Service. We would detail such terms if and when those features launch. In any case, if you voluntarily provide feedback, ideas, or suggestions to us (e.g., via email or forums), you agree that we can use and implement those ideas without any compensation to you and without any obligation to attribute them to you.</p>
              <p><strong>DMCA and Copyright Infringement:</strong> If you believe any content on Scavenjer infringes your copyright or other intellectual property rights, please contact us with a detailed notice. We respect intellectual property laws and will promptly investigate and address valid infringement claims. Repeat infringers' accounts may be terminated in appropriate circumstances. (For copyright notices under the U.S. Digital Millennium Copyright Act, include all required information, such as identification of the copyrighted work and the allegedly infringing content, your contact information, a statement of good faith, etc. We will provide an address or email for DMCA notices in our contact section or website.)</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Disclaimer of Warranties</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p><strong>Use At Your Own Risk:</strong> Scavenjer provides the Service on an “as is” and “as available” basis. To the maximum extent permitted by law, we disclaim all warranties of any kind (express or implied) regarding the Service and its content. This includes, but is not limited to, implied warranties of merchantability, fitness for a particular purpose, title, non-infringement, and any warranties that may arise from course of dealing or usage of trade. We make no guarantee that the Service will meet your requirements or expectations, or that it will achieve any intended results.</p>
              <p>Specifically, Scavenjer does not warrant or guarantee:</p>
              <ul className="list-disc pl-6 space-y-2">
                  <li><strong>Availability and Accuracy:</strong> That the Service (or any hunt or reward) will be available at all times, uninterrupted, secure, or free of errors, defects, viruses, or other harmful components. We do not warrant that information provided (including clue descriptions, locations, or reward details) is 100% accurate, complete, or up-to-date. While we endeavor to ensure a fun and reliable experience, technical issues or inaccuracies may occur, and we are not responsible for those.</li>
                  <li><strong>AR Functionality:</strong> That any augmented reality or location-based features (facilitated via Marbleverse or other technologies) will work flawlessly in all areas and on all devices. AR experiences by nature may be affected by environmental conditions or device capabilities. You may experience glitches, or AR content may not perfectly align with real world, etc. These are not guaranteed aspects of performance.</li>
                  <li><strong>Safety:</strong> While we require users to follow safety guidelines, we make no warranty that all users will do so or that the environments of hunts will be hazard-free. We do not inspect locations for safety or suitability; you must use your own judgment and caution.</li>
                  <li><strong>Reward Value or Function:</strong> Any digital asset or reward is provided without warranty of value, functionality, or continued availability. We do not guarantee that any digital reward will retain value, be transferable, or be usable outside our intended scope. We are also not responsible for any technical failures in the blockchain or Marbleverse that could affect your reward (e.g., network congestion, token disappearance, etc.).</li>
                  <li><strong>Third-Party Services:</strong> We make no warranties about third-party services integration. For example, we can't guarantee that Marbleverse or Supabase will have zero downtime or security breaches, though we choose reputable providers. Their content and performance are outside our direct control.</li>
              </ul>
              <p><strong>No Professional Advice:</strong> Any information or content in the Service (such as historical facts in a hunt, fitness tips if any, or location info) is for entertainment or general informational purposes only and should not be taken as professional advice. You should not rely on any information on the platform for medical, legal, financial, or other professional decisions. Always consult an appropriate professional for advice.</p>
              <p>In jurisdictions that do not allow the exclusion of certain warranties, some of the above disclaimers may not fully apply to you. In such cases, Scavenjer's warranties will be limited to the extent permitted by applicable law.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Limitation of Liability</h2>
            <div className="space-y-4 text-gray-300 text-base">
                <p><strong>Limitation on Types of Damages:</strong> To the fullest extent permitted by law, Scavenjer and its parent company, affiliates, officers, employees, agents, partners, and licensors will not be liable for any indirect, incidental, special, consequential, or exemplary damages, or any damages for loss of profits, revenues, goodwill, data, or other intangible losses, arising out of or related to your use of (or inability to use) the Service. This limitation applies to all causes of action, whether in contract, warranty, tort (including negligence), strict liability, or any other legal theory, even if we have been advised of the possibility of such damages.</p>
                <p><strong>Cap on Liability Amount:</strong> To the extent any liability is not legally disclaimable, the total liability of Scavenjer for any claim arising out of or relating to these Terms or the Service is limited to the greater of: (a) the amount you have paid to us for the Service in the 12 months immediately preceding the event giving rise to the claim (if any), or (b) USD $100. If applicable law does not allow the limitation of liability as set forth above, this provision shall be deemed modified solely to the extent necessary to comply with applicable law.</p>
                <div>
                    <p><strong>Specific Application:</strong> Without limiting the above, you agree that Scavenjer is not liable for:</p>
                    <ul className="list-disc pl-6 mt-2 space-y-2">
                        <li><strong>Personal Injuries or Property Damage:</strong> Any injury, death, or damage to property that may occur while you are participating in a scavenger hunt or using the Service. You assume all risks of walking around in the real world, interacting with environments, and engaging in the hunts. You release Scavenjer from any claims arising from such real-world activities. For example, if you trip and fall, get into an accident, or have a confrontation with someone while on a hunt, Scavenjer is not responsible. Similarly, if you trespass or break a rule and suffer consequences, that is solely on you.</li>
                        <li><strong>Third-Party Acts or Omissions:</strong> Any acts, errors, or omissions of third parties, including Marbleverse's platform failures, Supabase data breaches, third-party content inaccuracies, or other users' behavior. If another user or a third-party causes you harm or loss (for example, someone cheats or behaves maliciously, or a location on the map is not as described by a third-party source), we are not liable for those interactions. However, we encourage you to inform us of any bad behavior or issues, so we can take appropriate action within our platform.</li>
                        <li><strong>Loss of Digital Assets:</strong> Loss, theft, or inaccessibility of any digital asset reward once delivered to you. This includes losses due to your lost credentials, unauthorized access to your wallet, failures of the underlying blockchain, or Marbleverse shutting down or altering its services. We provide the conduit for you to receive the asset, but we cannot guarantee its perpetual existence or your ability to access it thereafter.</li>
                        <li><strong>Service Interruptions or Data Loss:</strong> Any interruption of Service, or loss/corruption of data. We make reasonable efforts to maintain uptime and protect user data (and we use Supabase which performs daily backups), but we do not guarantee that the Service will always be available or that data (like your progress or account information) will never be lost or compromised. Always keep your own records if something is important.</li>
                        <li><strong>Punitive Damages:</strong> We will not be liable for any punitive or exemplary damages, to the extent such can be disclaimed, as those are intended to punish wrongdoing beyond actual harm and we do not foresee circumstances where such damages would be applicable to a good-faith platform like ours.</li>
                    </ul>
                </div>
                <p><strong>No Liability for Certain Claims:</strong> We shall not be liable for any claims arising out of: (i) your violation of these Terms or law (in other words, if your own misconduct causes damage, we aren't paying for it); (ii) any content posted by third parties (including offensive or illegal content that might appear in a user communication or third-party link); (iii) the cost of procurement of substitute goods or services (e.g., if our Service is unavailable and you spend money on something else, we aren't responsible for those costs).</p>
                <p><strong>Carve-Out for Jurisdictions:</strong> Some jurisdictions do not allow the exclusion or limitation of certain damages. If you are in such a jurisdiction (for example, some states do not allow the exclusion of incidental or consequential damages), the above limitations may not apply to you to the extent prohibited. In such cases, our liability will be limited to the maximum extent permitted by law.</p>
                <p><strong>Intentional Misconduct and Gross Negligence:</strong> Nothing in these Terms shall limit or exclude our liability for our own intentional misconduct, willful violations of law, or gross negligence, or for any other liability that cannot be excluded under applicable law (such as certain statutory liabilities). Additionally, nothing in these Terms affects your statutory rights that cannot be waived or limited by contract.</p>
                <p>By using Scavenjer, you understand and agree that we are offering a fun, experimental platform and cannot be liable for all possible outcomes. You agree to take responsibility for your own actions and participation. If you do not agree with these limitations, please do not use the Service.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Indemnification</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>You agree to indemnify, defend, and hold harmless Scavenjer, its parent company (if any), affiliates, and each of their respective officers, directors, employees, agents, partners, and licensors (collectively, the "Scavenjer Parties") from and against any and all third-party claims, liabilities, damages, losses, and expenses (including reasonable attorneys' fees and costs) that arise out of or are related to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Your Use of the Service:</strong> Any use of Scavenjer (including the Marbleverse-related features) in violation of these Terms or in violation of any law or regulation.</li>
                <li><strong>Your Violation of These Terms:</strong> If you breach any provision of these Terms (for example, engaging in cheating, misconduct, or unauthorized content use) and that breach causes harm or expense to someone else or to us, you will be responsible for the costs.</li>
                <li><strong>Your Violation of Any Rights:</strong> Any claim that your conduct or content (if user content becomes applicable) infringes or misappropriates any intellectual property, privacy, publicity, or other right of a third party. For instance, if you somehow submit content you don't have rights to and a copyright owner sues us, you agree to cover our costs.</li>
                <li><strong>Your Interactions and Activities:</strong> Any disputes or incidents between you and other users or third parties that occur through your use of Scavenjer. For example, if you get into a dispute with a property owner or another participant during a hunt and they bring a claim against us due to something you did, you'll indemnify us for that. Similarly, if you defraud someone or engage in unlawful behavior that implicates Scavenjer, you will hold us harmless.</li>
              </ul>
              <p>We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you (meaning, we might choose to handle a legal defense ourselves even if it's because of your actions), and in such case, you agree to cooperate with our defense of that claim. You agree not to settle any such matter without the prior written consent of Scavenjer. We will use reasonable efforts to notify you of any such claim, action, or proceeding as soon as we become aware of it.</p>
              <p>Your indemnification obligations will survive any termination of your relationship with Scavenjer or cessation of use of the Service. In plain terms, if you do something that gets Scavenjer sued or fined, you agree to cover our costs (unless we are also at fault to a degree that your local law would not require you to indemnify us fully).</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Suspension and Termination</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p><strong>By Scavenjer:</strong> We reserve the right to suspend or terminate your access to the Service (in whole or in part) at our discretion, with or without prior notice, if you violate these Terms or if we suspect fraudulent, abusive, or unlawful activity on your account. We may also suspend the Service or your account if required to do so by law enforcement or if there are security issues. In serious cases of Terms violations or harm to other users, termination may be immediate and without prior warning. Effects of Termination by Scavenjer may include: (a) your account being disabled or deleted; (b) your access to any hunts or content being cut off; (c) your entitlement to any unclaimed rewards being revoked (especially if termination was due to misconduct). If we terminate your account and you believe it was wrongful or in error, you may contact us to request a review, but we reserve the final decision. Note that no refunds will be provided for any unused subscription period if you are terminated for cause (violation of Terms).</p>
              <p><strong>By You (Account Deletion):</strong> You are free to stop using Scavenjer at any time. If you wish to delete your account, you may do so through the account settings (if available) or by contacting us at our support email. Deleting your account will remove your personal data from active use and disable your profile. However, certain data may be retained as required or permitted by law (see Privacy Policy for data retention details) and for backup or archival purposes. If you had any earned rewards prior to deletion, those digital assets should remain in your linked wallet (they are yours to keep), but you may lose any in-app record or proof of those rewards once the account is deleted.</p>
              <p><strong>Service Termination:</strong> We also reserve the right to discontinue or shutdown the Scavenjer Service itself (or any part of it) at any time, for any reason (for example, if we decide to end the project, or due to business reasons, or technical constraints). If we anticipate a permanent shutdown, we will make reasonable efforts to inform users in advance via the app/website or email. In the event of a discontinuation, these Terms will also terminate (except for provisions that are meant to survive, like intellectual property rights, disclaimers, liability limitations, etc.). If a shutdown occurs, we will attempt to allow users to claim any outstanding rewards before closing, but cannot guarantee this if circumstances (like legal orders or insolvency) prevent it.</p>
              <p><strong>Survival:</strong> All provisions of these Terms which by their nature should survive termination (such as intellectual property ownership, warranty disclaimers, limitation of liability, indemnity, governing law, etc.) will survive the termination of your access or of these Terms. Terminating your account or stopping use of Scavenjer does not necessarily relieve you of any obligations incurred or arising prior to termination. For example, if while using the service you caused damage or incurred liability, that accountability continues even after your account is gone.</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Governing Law and Dispute Resolution</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p><strong>Governing Law:</strong> These Terms and any dispute or claim arising out of or in connection with these Terms or the use of the Service shall be governed by and construed in accordance with the laws of the State of Texas, USA, without regard to its conflict of law principles. If you reside outside of the United States, you understand and agree that U.S. (and specifically Texas) law will apply to the interpretation of these Terms. However, we respect that mandatory consumer protection laws of your country of residence may still apply for your benefit where applicable, and nothing in these Terms seeks to limit those rights.</p>
              <p><strong>Jurisdiction and Venue:</strong> Subject to any arbitration provision or other dispute mechanism described below (if applicable), you and Scavenjer agree that any judicial proceeding to resolve claims relating to these Terms or the Service will be brought in the federal or state courts located in the State of Texas, U.S.A., specifically in the jurisdiction of our choosing (likely the courts nearest our company's principal place of business, e.g., in Texas). Both you and Scavenjer consent to the exclusive jurisdiction and venue of such courts. You waive any objections to such jurisdiction or venue, including on grounds of forum non conveniens (unless you are prohibited by law from agreeing to this, for example, if you are a consumer in an EU member state, you may have the right to bring claims in your country of residence).</p>
              <p><strong>Arbitration and Class Action Waiver (if applicable):</strong> At this time, we have not instituted a mandatory arbitration clause in these Terms. We prefer to resolve issues amicably and through normal legal processes if necessary. However, we reserve the right to introduce an arbitration agreement and class action waiver in future updates to these Terms, which would apply to disputes on a going-forward basis (with an opt-out opportunity for existing users). If we do so, we will provide clear notice and you will have the option to accept the updated Terms or cease using the Service. In the meantime, nothing herein waives either party's right to a trial by jury except as voluntarily agreed or required by law.</p>
              <p><strong>Informal Resolution:</strong> Before filing any formal legal claim against Scavenjer, we request that you first contact us at our support email (provided in the Contact section) with a brief written description of the dispute and your contact information. Many concerns can be resolved quickly and to everyone's satisfaction through dialogue. We will do our best to respond to and address your concerns. Both you and we agree to attempt in good faith to negotiate a resolution for at least 30 days before resorting to formal legal proceedings or arbitration.</p>
              <p><strong>Time Limit on Claims:</strong> To the extent permitted by law, any claim or cause of action you may have arising out of or related to these Terms or the Service must be filed within one (1) year after such claim or cause of action arose; otherwise, your claim is permanently barred. (This does not apply to users in jurisdictions that prohibit shortening of statutory limitation periods.)</p>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Miscellaneous Provisions</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <ul className="list-disc pl-6 space-y-3">
                <li><strong>Entire Agreement:</strong> These Terms (along with the Privacy Policy and any additional guidelines, rules, or terms posted in specific sections of the Service) constitute the entire agreement between you and Scavenjer regarding your use of the Service, and supersede any prior agreements or understandings between us, whether written or oral, relating to such subject matter. Any additional or different terms proposed by you (for example, in an email or purchase order) are expressly rejected and will have no effect unless agreed to by Scavenjer in writing.</li>
                <li><strong>Severability:</strong> If any provision of these Terms is held to be unlawful, void, or unenforceable by a court of competent jurisdiction, then that provision shall be deemed severable from the Terms and shall not affect the validity and enforceability of any remaining provisions. The invalid provision will be deemed modified so as to be enforceable to the maximum extent permitted by law, reflecting the intent of the original provision as closely as possible.</li>
                <li><strong>No Waiver:</strong> Our failure to enforce any right or provision of these Terms will not be considered a waiver of those rights. A waiver by Scavenjer of any term or condition set forth in these Terms in any instance shall not be deemed a further or continuing waiver of such term or condition or a waiver of any other term or condition, and any failure of Scavenjer to assert a right or provision under these Terms shall not constitute a waiver of such right or provision.</li>
                <li><strong>Assignment:</strong> You may not assign or transfer these Terms (or any of your rights or obligations hereunder) without our prior written consent. We may assign or transfer these Terms or any rights or obligations hereunder to any third party at our discretion, including in connection with a merger, acquisition, reorganization, or sale of assets, or by operation of law. These Terms will bind and inure to the benefit of the parties, their successors, and permitted assigns.</li>
                <li><strong>Relationship of Parties:</strong> You and Scavenjer are independent contracting parties. These Terms do not create any agency, partnership, joint venture, employment, or franchise relationship. You have no authority to bind or obligate Scavenjer in any manner.</li>
                <li><strong>Force Majeure:</strong> Scavenjer will not be liable for any delay or failure to perform as required by these Terms because of any cause or condition beyond our reasonable control, including but not limited to any acts of God, natural disasters, war, terrorism, labor conditions, power failures, internet disturbances, or government actions.</li>
                <li><strong>Notices:</strong> We may provide notices or communications to you by email (to the address associated with your account), through the Service (e.g., via in-app notification), or by posting on our website. You consent to receive electronic communications from us. You are responsible for maintaining a current email address on file. If you need to give us notice, you can do so via the contact information provided below.</li>
                <li><strong>Headings:</strong> Section headings in these Terms are for convenience only and have no legal or contractual effect.</li>
                <li><strong>Language:</strong> These Terms may be provided in languages other than English for convenience and local requirements. However, the English version of these Terms will prevail in case of any conflict or discrepancy in interpretation.</li>
              </ul>
            </div>
          </section>

          <section className="bg-[#111111]/90 rounded-lg p-8 border border-[#2DD4BF]/20">
            <h2 className="text-2xl font-bold text-[#2DD4BF] mb-4">Contact Information</h2>
            <div className="space-y-4 text-gray-300 text-base">
              <p>If you have any questions, concerns, or comments about these Terms or the Scavenjer Service, or if you need to reach us for any reason, please contact us as follows:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li><strong>Email:</strong> <a href="mailto:support@scavenjer.com" className="text-[#2DD4BF] hover:underline">support@scavenjer.com</a> (Note: This is an example contact email. Please use the actual support email provided in the Scavenjer app or website.)</li>
                <li><strong>Mailing Address:</strong> Scavenjer (Attn: Legal), [1234 Street Name, City, State, Postal Code, Country] (Note: Add an actual physical address here if available.)</li>
              </ul>
              <p>We will do our best to respond to inquiries promptly. If you are contacting us to report a violation of these Terms or to raise a dispute, please provide as much detail as possible, including relevant screenshots or facts, so we can address the issue effectively.</p>
              <p>Thank you for reading these Terms and for being a part of Scavenjer. We hope you enjoy exploring the world through our scavenger hunts. Happy hunting!</p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}